config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'users/profile'
  post 'users/add_product'
  post 'users/remove_product'

  get :autocomplete_product_name, to: 'products#autocomplete_product_name'
  get 'find/(page/:page)', to: 'products#find', as: :find
  resources :products, only: [:show], param: :url_name

  root 'welcome#index'

  resources :groups, only: [:index, :show], param: :name
  resources :categories, only: [:index, :show], param: :category_name

  get 'info', to: 'info#stats'
  get 'xhr_stats', to: 'info#xhr_stats'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :products
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :products
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :product
  belongs_to :seller
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_and_belongs_to_many :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :costs
  has_many :sellers, through: :costs

  has_and_belongs_to_many :carts

  validates :name, presence: true

  def prices
    if self.max_price != self.min_price
      price_to_s(self.min_price) + ' - ' + price_to_s(self.max_price) + ' руб.'
    elsif self.max_price == self.min_price
      price_to_s(self.min_price) + ' руб.'
    end
  end

  private

  def price_to_s(price)
    price.to_s.reverse.scan(/\d{1,3}/).join(' ').reverse.strip
  end
  
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :costs
  has_many :products, through: :costs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart

  after_create :add_cart_for_user

  def add_cart_for_user
    self.create_cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.where.not(products_quantity: nil).order('name_ru ASC')
  end

  def show
    @category = Category.find_by(name: params[:category_name])
    @products = @category.products.page(params[:page])
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.order('name_ru ASC')
  end

  def show
    @group = Group.find_by(name: params[:name])
    @categories = @group.categories.order('name_ru ASC')
  end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  # before_filter :authenticate_user!
  # before_filter do 
  #   redirect_to :new_user_session_path unless current_user && current_user.admin?
  # end

  def stats
  end

  def xhr_stats
    @groups = Group.count
    @categories = Category.count
    @products_in_stock = Product.where.not(min_price: nil).count
    @products_in_stock_uniq = Product.select(:url_name).distinct.where.not(min_price: nil).count
    @products_all = Product.count
    @products_all_uniq = Product.select(:url_name).distinct.count
    @users = User.count
    render template: "info/xhr_stats.html.erb", layout: false
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def find
    @request = params[:form][:product]
    if @request.length < 2
      redirect_to :back
    else
      if params[:form][:out] == '0'
        products = Product.where("name like ?", "#{@request}%").where.not(min_price: nil).group(:url_name)
      else
        products = Product.where("name like ?", "#{@request}%").group(:url_name)
      end
      @amount = products.count.count
      @products = products.page(params[:page])
    end
  end

  def autocomplete_product_name
    term = params[:term]
    products = Product.select(:name).distinct.where('name LIKE ?', "#{term}%").take(10)
    render json: products.map { |product| {id: product.id, label: product.name, value: product.name} }
  end

  def show
    @product = Product.find_by(url_name: params[:url_name])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def profile
    @email = current_user.email
    @products = current_user.cart.products.page(params[:page])
  end

  def add_product
    product_id = params[:product_id].to_i
    ids = current_user.cart.products.pluck(:id)
    current_user.cart.products << Product.find(product_id) unless ids.include?(product_id)
    render json: current_user.cart.products.count
  end

  def remove_product
    product_id = params[:product_id].to_i
    current_user.cart.products.delete(Product.find(product_id))
    render json: current_user.cart.products.count
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @date = 
      if Group.exists?
        time = Group.last.created_at
        [time.day, time.month, time.year].map { |t| t.to_s.rjust(2, '0') }.join('.')
      end || nil
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.slim
h1 Категории продуктов
hr

- @categories.each_slice(4) do |slice|
  .row
    - slice.each do |category|
      .col-lg-3
        = link_to category.name_ru, category_path(category.name)
  br

app/views/categories/show.html.erb
<h1><%= "#{@category.name_ru}" %><%= " (#{@category.products_quantity} продукта(ов))" if @category.products_quantity %></h1>
<hr>

<%= render 'shared/products' %>

app/views/groups/_categories_in_slices.html.erb
<% @categories.each_slice(4) do |slice| %>
  <div class="row">
    <% slice.each do |category| %>
      <div class="col-lg-3">
        <%= link_to category.name_ru, category_path(category.name) %>
      </div>
    <% end %>
  </div>
  <br>
<% end %>

app/views/groups/index.html.erb
<h1>Группы категорий</h1>
<hr>

<% @groups.each_slice(4) do |slice| %>
  <div class='row'>
    <% slice.each do |group| %>
      <div class='col-lg-3'>
        <%= link_to group.name_ru, group_path(name: group.name) %>
      </div>
    <% end %>
  </div>
  <br>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name_ru %></h1>
<hr>

<%= render 'categories_in_slices' %>

app/views/products/find.html.erb
<h1>По запросу "<%= "#{@request}"%>" найдено продуктов: <%= "#{@amount}" %></h1>
<hr>

<%= render 'shared/products' %>

app/views/products/show.html.slim
h1 = @product.name
hr

div class="row product-row"
  div class="col-lg-3"
    = image_tag @product.large_image_url
  div class="col-lg-9"
    = @product.description
    br
    - if @product.min_price
      | цена: 
      = @product.prices
      br
    = link_to 'Каталог Onliner', @product.url, target: "_blank"
    - if user_signed_in?
      div
        div class="add-favorite" title="Добавить в интересуемое" +     

app/views/users/_profile_products.slim
.profileProducts
  = paginate @products, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

  - @products.each do |product|
    .row.product-row

      .col-lg-3
        = image_tag product.small_image_url

      .col-lg-8
        = link_to product.name, product.url, target: "_blank"
        - if product.description?
          div = product.description
        - if product.min_price
          div
            | цена: 
            = product.prices

      .col-lg-1
        .remove-favorite data-id=product.id title="Убрать" -
    br
        
  = paginate @products, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/users/profile.html.slim
h1 Профиль
hr

= render 'profile_products'

javascript:
  $(document).ready(function() {
    $('.remove-favorite').click(function() {
      var productId = this.dataset.id;
      $.ajax({
        url: "#{users_remove_product_path}",
        type: "POST",
        data: {
          product_id: productId
        },
        success: function(jsonResponse) {
          var newUserProductsQuantity = JSON.parse(jsonResponse),
              accountEmail = $('#account-link').html().split(' ')[0];
          $('#account-link').html(accountEmail + ' (' + newUserProductsQuantity + ')');
        }        
      });
    });
  });