config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'users/profile'
  post 'users/add_product'
  post 'users/remove_product'

  get :autocomplete_product_name, to: 'products#autocomplete_product_name'
  get 'find/(page/:page)', to: 'products#find', as: :find
  resources :products, only: [:show], param: :url_name

  root 'welcome#index'

  resources :groups, only: [:index, :show], param: :name
  resources :categories, only: [:index, :show], param: :category_name

  get 'info', to: 'info#stats'
  get 'xhr_stats', to: 'info#xhr_stats'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :products
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :products
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :product
  belongs_to :seller
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_and_belongs_to_many :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :costs
  has_many :sellers, through: :costs

  has_and_belongs_to_many :carts

  validates :name, presence: true

  def prices
    if self.max_price != self.min_price
      price_to_s(self.min_price) + ' - ' + price_to_s(self.max_price) + ' руб.'
    elsif self.max_price == self.min_price
      price_to_s(self.min_price) + ' руб.'
    end
  end

  private

  def price_to_s(price)
    price.to_s.reverse.scan(/\d{1,3}/).join(' ').reverse.strip
  end
  
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :costs
  has_many :products, through: :costs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart

  after_create :add_cart_for_user

  def add_cart_for_user
    self.create_cart
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.order('name_ru ASC')
  end

  def show
    @group = Group.find_by(name: params[:name])
    @categories = @group.categories.order('name_ru ASC')
  end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  # before_filter :authenticate_user!
  # before_filter do 
  #   redirect_to :new_user_session_path unless current_user && current_user.admin?
  # end

  def stats
  end

  def xhr_stats
    @groups = Group.count
    @categories = Category.count
    @products_in_stock = Product.where.not(min_price: nil).count
    @products_in_stock_uniq = Product.select(:url_name).distinct.where.not(min_price: nil).count
    @products_all = Product.count
    @products_all_uniq = Product.select(:url_name).distinct.count
    @users = User.count
    render template: "info/xhr_stats.html.erb", layout: false
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def find
    @request = params[:form][:product]
    if @request.length < 2
      redirect_to :back
    else
      if params[:form][:out] == '0'
        products = Product.where("name like ?", "#{@request}%").where.not(min_price: nil).group(:url_name)
      else
        products = Product.where("name like ?", "#{@request}%").group(:url_name)
      end
      @amount = products.count.count
      @products = products.page(params[:page])
    end
  end

  def autocomplete_product_name
    term = params[:term]
    products = Product.select(:name).distinct.where('name LIKE ?', "#{term}%").take(10)
    render json: products.map { |product| {id: product.id, label: product.name, value: product.name} }
  end

  def show
    @product = Product.find_by(url_name: params[:url_name])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def profile
    @email = current_user.email
    @products = current_user.cart.products.page(params[:page])
  end

  def add_product
    product_id = params[:product_id].to_i
    ids = current_user.cart.products.pluck(:id)
    current_user.cart.products << Product.find(product_id) unless ids.include?(product_id)
    render json: current_user.cart.products.count
  end

  def remove_product
    product_id = params[:product_id].to_i
    current_user.cart.products.delete(Product.find(product_id))
    render json: current_user.cart.products.count
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @date = 
      if Group.exists?
        time = Group.last.created_at
        [time.day, time.month, time.year].map { |t| t.to_s.rjust(2, '0') }.join('.')
      end || nil
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/info/stats.html.erb
<h1>Статистика</h1>
<hr>
<input id="button" type="button" value="Обновить" disabled="disabled" autocomplete="off" onclick="getStats();" class="btn btn-primary">
<p>
  <div id="info"></div>
  <div class="progress" id="loading" style="visibility: hidden">
    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
  </div>
</p>

<script type="text/javascript">
  function getStats(){
    var info = document.getElementById('info'),
        loading = document.getElementById('loading'),
        button = document.getElementById('button');
    var xhr = new XMLHttpRequest();
    xhr.open("GET", "<%= xhr_stats_path %>", true);
    xhr.onload = function () {
      info.innerHTML = xhr.responseText;
      loading.style.visibility = 'hidden';
      button.removeAttribute("disabled"); 
    };
    xhr.send();
    info.innerHTML = 'Сбор информации...';
    loading.style.visibility = 'visible';
    button.setAttribute('disabled', 'disabled');
  }
  getStats();
</script>

app/views/info/xhr_stats.html.erb
<div>Групп: <%= @groups %></div>
<div>Категорий: <%= @categories %></div>
<div>Продуктов в продаже: <%= "#{@products_in_stock} (уникальных #{@products_in_stock_uniq})" %></div>
<div>Продуктов всего: <%= "#{@products_all} (уникальных #{@products_all_uniq})" %></div>
<div>Пользователей зарегистрировано: <%= "#{@users}" %></div>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/welcome/index.html.slim
h1 Railiner
hr

div
  ' Продукты
  = link_to 'catalog.onliner.by', 'http://catalog.onliner.by', target: '_blank'
  | . Добро пожаловать!
  
- if @date
  div 
    | База данных от 
    = @date