config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'users/profile'
  post 'users/add_product'
  post 'users/remove_product'

  get :autocomplete_product_name, to: 'products#autocomplete_product_name'
  get 'find/(page/:page)', to: 'products#find', as: :find
  resources :products, only: [:show], param: :url_name

  root 'welcome#index'

  resources :groups, only: [:index, :show], param: :name
  resources :categories, only: [:index, :show], param: :category_name

  get 'info', to: 'info#stats'
  get 'xhr_stats', to: 'info#xhr_stats'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :products
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :products
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :product
  belongs_to :seller
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_and_belongs_to_many :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :costs
  has_many :sellers, through: :costs

  has_and_belongs_to_many :carts

  validates :name, presence: true

  def prices
    if self.max_price != self.min_price
      price_to_s(self.min_price) + ' - ' + price_to_s(self.max_price) + ' руб.'
    elsif self.max_price == self.min_price
      price_to_s(self.min_price) + ' руб.'
    end
  end

  private

  def price_to_s(price)
    price.to_s.reverse.scan(/\d{1,3}/).join(' ').reverse.strip
  end
  
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :costs
  has_many :products, through: :costs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart

  after_create :add_cart_for_user

  def add_cart_for_user
    self.create_cart
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.order('name_ru ASC')
  end

  def show
    @group = Group.find_by(name: params[:name])
    @categories = @group.categories.order('name_ru ASC')
  end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  # before_filter :authenticate_user!
  # before_filter do 
  #   redirect_to :new_user_session_path unless current_user && current_user.admin?
  # end

  def stats
  end

  def xhr_stats
    @groups = Group.count
    @categories = Category.count
    @products_in_stock = Product.where.not(min_price: nil).count
    @products_in_stock_uniq = Product.select(:url_name).distinct.where.not(min_price: nil).count
    @products_all = Product.count
    @products_all_uniq = Product.select(:url_name).distinct.count
    @users = User.count
    render template: "info/xhr_stats.html.erb", layout: false
  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def profile
    @email = current_user.email
    @products = current_user.cart.products.page(params[:page])
  end

  def add_product
    product_id = params[:product_id].to_i
    ids = current_user.cart.products.pluck(:id)
    current_user.cart.products << Product.find(product_id) unless ids.include?(product_id)
    render json: current_user.cart.products.count
  end

  def remove_product
    product_id = params[:product_id].to_i
    current_user.cart.products.delete(Product.find(product_id))
    render json: current_user.cart.products.count
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Продукты catalog.onliner.by" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all", type: "text/css" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
    <!-- <div class="navbar navbar-default navbar-fixed-top"> -->
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Railiner</a>

        <%= form_for :form, url: find_path, method: :get, html: {"class" => 'navbar-form navbar-left form-inline'} do |f| %>
          <div class="form-group">
            <%= f.autocomplete_field :product, autocomplete_product_name_path, placeholder: "Найти продукт", class: "form-control" %>
          </div>
            <%= f.submit 'Найти', class: "btn btn-primary" %>
            <%= f.check_box 'out' %> + не в продаже
        <% end %>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            <li><%= link_to "Группы", "/groups" %></li>
            <li><%= link_to "Категории", "/categories" %></li>
            <li><%= link_to "Информация", "/info" if user_signed_in? && current_user.admin? %></li>

            <% if user_signed_in? %>
              <li><%= link_to "#{current_user.email} (#{current_user.cart.products.count})", users_profile_path, id: 'account-link' %></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Войти', new_user_session_path %></li>
              <li><%= link_to 'Регистрация', new_user_registration_path %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>

    <script>
      $(document).ready(function() {
        setInterval(function(){
          $('.alert').slideUp(300);
        }, 2000);
      });
    </script>

  </body>
</html>

app/views/shared/_products.html.slim
= paginate @products, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

- @products.each do |product|
  .row.product-row
    .col-lg-3
      = image_tag product.small_image_url
    .col-lg-8

      div = link_to product.name, product_path(url_name: product.url_name)

      - if product.description?
        div = product.description

      - if product.min_price
        div
          | цена: 
          = product.prices

    - if user_signed_in?
      .col-lg-1
        .add-favorite data-id=product.id title="Добавить в интересуемое" +
  br

= paginate @products, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

javascript:
  $(document).ready(function() {
    $('.add-favorite').click(function() {
      var productId = this.dataset.id;
      $.ajax({
        url: "#{users_add_product_path}",
        type: "POST",
        data: {
          product_id: productId
        },
        success: function(jsonResponse) {
          var newUserProductsQuantity = JSON.parse(jsonResponse),
              accountEmail = $('#account-link').html().split(' ')[0];
          $('#account-link').html(accountEmail + ' (' + newUserProductsQuantity + ')');
        }        
      });
    });
  });